version: "3.0"

services:

  api:
    image: moleculer/demo
    restart: unless-stopped
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    labels:
    - traefik.http.routers.api.rule=Host('api.localhost')
    - traefik.port=80
    - traefik.enable=true
    networks:
      - internal
      - web
    depends_on:
      - nats

  greeter:
    image: moleculer/demo
    restart: unless-stopped
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    depends_on:
      - nats

  calc:
    image: moleculer/demo
    restart: unless-stopped
    env_file: docker-compose.env
    environment:
      SERVICES: calc
    depends_on:
      - nats

  products:
    image: moleculer/demo
    restart: unless-stopped
    env_file: docker-compose.env
    environment:
      SERVICES: products
    depends_on:
      - nats
      - mongo

  # NATS for transporter
  nats:
    image: nats
    ports:
      - "4222:4222"
    restart: unless-stopped

  # Database store
  mongo:
    image: mongo
    volumes:
      - db:/data/db
    restart: unless-stopped

  # Reverse proxy for API server
  traefik:
    image: traefik:v2.4
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml

volumes:
  db:
    driver: local

networks:
  web:
    external: true
  internal:
    external: false