---
#########################################################
# Service for Moleculer API Gateway service
#########################################################
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: moleculer-demo-api
  ports:
  - port: 3000
    targetPort: 3000

---
#########################################################
# Ingress for Moleculer API Gateway
#########################################################
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: moleculer.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: api
          servicePort: 3000

---
#########################################################
# API Gateway service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moleculer-demo-api
spec:
  selector:
    matchLabels:
      app: moleculer-demo-api
  replicas: 2
  template:
    metadata:
      labels:
        app: moleculer-demo-api
    spec:
      containers:
      - name: moleculer-demo-api
        image: moleculer/demo:1.2.0
        env:
          - name: SERVICEDIR
            value: services
          - name: SERVICES
            value: api
          - name: TRANSPORTER
            value: nats://nats:4222

---
#########################################################
# Greeter service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moleculer-demo-greeter
spec:
  selector:
    matchLabels:
      app: moleculer-demo-greeter
  replicas: 2
  template:
    metadata:
      labels:
        app: moleculer-demo-greeter
    spec:
      containers:
      - name: moleculer-demo-greeter
        image: moleculer/demo:1.2.0
        env:
          - name: SERVICEDIR
            value: services
          - name: SERVICES
            value: greeter
          - name: TRANSPORTER
            value: nats://nats:4222          

---
#########################################################
# Calc service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moleculer-demo-calc
spec:
  selector:
    matchLabels:
      app: moleculer-demo-calc
  replicas: 2
  template:
    metadata:
      labels:
        app: moleculer-demo-calc
    spec:
      containers:
      - name: moleculer-demo-calc
        image: moleculer/demo:1.2.0
        env:
          - name: SERVICEDIR
            value: services
          - name: SERVICES
            value: calc
          - name: TRANSPORTER
            value: nats://nats:4222               

---
#########################################################
# Products service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moleculer-demo-products
spec:
  selector:
    matchLabels:
      app: moleculer-demo-products
  replicas: 2
  template:
    metadata:
      labels:
        app: moleculer-demo-products
    spec:
      containers:
      - name: moleculer-demo-products
        image: moleculer/demo:1.2.0
        env:
          - name: SERVICEDIR
            value: services
          - name: SERVICES
            value: products
          - name: TRANSPORTER
            value: nats://nats:4222
          - name: MONGO_URI
            value: mongodb://mongo:27017/moleculer-demo              

---
#########################################################
# NATS transporter service
#########################################################
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  ports:
  - port: 4222
    name: nats
    targetPort: 4222

---
#########################################################
# NATS transporter
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
spec:
  selector:
    matchLabels:
      app: nats
  replicas: 1
  strategy:
    type: Recreate  
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats
        ports:
        - containerPort: 4222
          name: nats

---
#########################################################
# Mongo database
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data

---
#########################################################
# Persistent volume
#########################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  labels:
    name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: local-path
  resources:
    requests:
      storage: 100Mi

---
#########################################################
# Mongo database service
#########################################################
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo          

---
#########################################################
# Horizontal Pod AutoScaler for API service (K8s >= v1.17)
#########################################################
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-service-calc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: moleculer-demo-calc
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50