# defaultEntryPoints must be at the top because it should not be in any table below
defaultEntryPoints = ["http", "https"]

## Logs
[log]
    level = "DEBUG"

[api]
  debug = true
  dashboard = true
  [api.statistics]
    recentErrors = 10

# Entrypoints, http and https
[entryPoints]

# http should be redirected to https
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.http.redirections.entryPoint]
      to = "https"
      scheme = "https"

# https is the default
  [entryPoints.https]
    address = ":443"
  [entryPoints.https.http.tls]
    certResolver = "myresolver"
    [[entryPoints.https.http.tls.domains]]
        main = "m.almasri622.knawat.io"
  [entryPoints.dashboard]
    address = ":8080"

# Enable ACME (Let's Encrypt): automatic SSL
[certificatesResolvers.myresolver.acme]
  email = "it@knawat.com"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.tlsChallenge]

[providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false
    domain = "m.almasri622.knawat.io"

[providers.file]
    filename = "traefik_dynamic.toml"