
[entryPoints]
  [entryPoints.web]
    address = ":80"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  network = "web"
  exposedByDefault = false


[log]
  level = "DEBUG"

[api]
  dashboard = true

[providers.file]
  filename = "traefik_dynamic.toml"





